  name: Deploy to DigitalOcean

  on:
    push:
      branches: [ master ]

  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        
        - name: Install doctl
          uses: digitalocean/action-doctl@v2
          with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        
        - name: Write SSH keys
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.DROPLET_IP }} > ~/.ssh/known_hosts
        
        - name: Copy all files to droplet #with defined folder in .bashrc
          run: doctl compute ssh ${{ secrets.DROPLET_ID }} --ssh-command "git pull origin master"
        
        - name: Install dependencies on droplet
          run: doctl compute ssh ${{ secrets.DROPLET_ID }} --ssh-command "pip install -r requirements.txt"
        
        - name: Run bot.py on droplet
          run: doctl compute ssh ${{ secrets.DROPLET_ID }} --ssh-command "python bot.py"
