  name: Deploy to DigitalOcean

  on:
    push:
      branches: [ master ]

  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        
        - name: Install doctl
          uses: digitalocean/action-doctl@v2
          with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        
        - name: Write SSH keys
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.DROPLET_IP }} > ~/.ssh/known_hosts
        
        - name: Copy all files to droplet
          run: doctl compute ssh ${{ secrets.DROPLET_ID }} -- git clone https://github.com/FanaticExplorer/DigitalOceanAutoBotTest
        
        - name: Install dependencies on droplet
          run: doctl compute ssh root@${{ secrets.DROPLET_PRIVATE_IP }} -- pip install -r /vdb/requirements.txt
        
        - name: Run bot.py on droplet
          run: doctl compute ssh root@${{ secrets.DROPLET_PRIVATE_IP }} -- python /vdb/bot.py
